version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/www/app/
      - /www/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      GEEKDISQ_REDIS_DEV: app.redis.local
    command: ['npm', 'start']
    container_name: app.app.local

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: app.redis.local